spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pokemon
    username: postgres
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
server:
  error:
    include-message: always
    include-exception: false